<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'easypeasyics' => '/extras/EasyPeasyICS.php',
                'ntlm_sasl_client_class' => '/extras/ntlm_sasl_client.php',
                'phpmailer' => '/class.phpmailer.php',
                'phpmailerexception' => '/class.phpmailer.php',
                'phpmaileroauth' => '/class.phpmaileroauth.php',
                'phpmaileroauthgoogle' => '/class.phpmaileroauthgoogle.php',
                'pop3' => '/class.pop3.php',
                'smtp' => '/class.smtp.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
